theme: jekyll-theme-minimal
# see here:
# https://github.com/pages-themes/minimal
# https://pages-themes.github.io/minimal
title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

# OLD CODE BY EKKE
# title: "Remote theme example"
# remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
# search_enabled: false
