theme: jekyll-theme-minimal
# see here:
# https://github.com/pages-themes/minimal
# https://pages-themes.github.io/minimal

# title: "Remote theme example"
# remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
# search_enabled: false
