title: Agenda 2021-22 
logo: Cessda_logo_grey_footer.png
description: Training Task 2 "Journals Outreach"
show_downloads: false
theme: jekyll-theme-minimal
#Instructions:
# https://github.com/pages-themes/minimal#usage

# see here:
# https://github.com/pages-themes/minimal
# https://pages-themes.github.io/minimal

# OLD CODE BY EKKE
# title: "Remote theme example"
# remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
# search_enabled: false
