title: CESSDA Training Task 2: Journals Outreach
logo: https://www.cessda.eu/design/cessda/image/logo/Cessda_logo_grey_footer.png
description: Journals Outreach info info info
show_downloads: true
theme: jekyll-theme-minimal
# see here:
# https://github.com/pages-themes/minimal
# https://pages-themes.github.io/minimal

# OLD CODE BY EKKE
# title: "Remote theme example"
# remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
# search_enabled: false
