# Site settings
title: Journals Outreach
logo: Cessda_logo_grey_footer.png
description: Agenda 2021-22 (Training Task 2)

description: <h3>Agenda 2021-22 (Training Task 2)</h3>
             <b>Open forum! Challenges of sharing data linked to publications</b>
             <i>Wednesday 30th June 2021, 13:00-15:50 CET online (zoom)</i>
             <a href="https://us02web.zoom.us/meeting/register/tZctdOyhqT4tH9DubmQ3qKwI8_s1lxkQ4xhx">Registration Form</a>

theme: jekyll-theme-minimal
show_downloads: false
footer: false
layout: default
sidebar: true
toc: true

#Instructions:
# https://github.com/pages-themes/minimal#usage

# see here:
# https://github.com/pages-themes/minimal
# https://pages-themes.github.io/minimal

# OLD CODE BY EKKE
# title: "Remote theme example"
# remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
# search_enabled: false
