# Site settings
title: Journals Outreach
logo: Cessda_logo_grey_footer.png
description: Agenda 2021-22 (Training Task 2)

description: To join our mailing list for future events and good practice, please send an email with your full name and affiliation to: <a href="journals-data+subscribe@cessda.eu">journals-data+subscribe@cessda.eu</a>
             <p>
             <h3><a href="https://www.cessda.eu/About" target="_blank"> Agenda 2021-22 (Training Task 2) </a></h3>
             <b>Open forum! Challenges of sharing data linked to publications</b>
             <i>Wednesday 30th June 2021, 13:00-15:50 CET online </i>
             <b>Event completed <a href="https://cessdajournalsoutreach.github.io/OpenForum" target="_blank"> More information </a></b>

theme: jekyll-theme-minimal
show_downloads: false
footer: false
layout: default
sidebar: true
toc: true

#Instructions:
# https://github.com/pages-themes/minimal#usage

# see here:
# https://github.com/pages-themes/minimal
# https://pages-themes.github.io/minimal

# OLD CODE BY EKKE
# title: "Remote theme example"
# remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
# search_enabled: false
